spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://com.wxsk.platform.db:3306/platform?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: tomcat
    password: 1Lk_6Ao_3XhG6_6f
    maxActive: 200
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    cluster:
      nodes: redis.cloud.server1:6379,redis.cloud.server2:6380,redis.cloud.server3:6381,redis.cloud.server4:6382,redis.cloud.server5:6383,redis.cloud.server6:6384

application:
  dubbo:
    applicationName: wxsk_game_platform
    registryAddress: zookeeper://zookeeper.server1:2181?backup=zookeeper.server2:2181,zookeeper.server3:2181
    port: 20906